@startuml

namespace MGReader {
    class User {
        -id: int
        +name: string
        +facebookStatus: string

        +login(fbs : FacebookSDK)
        +logout(fbs : FacebookSDK)
    }

    class FacebookSDK {
        +login()
        +logout()
    }

    class Manga {
        -id: int
        +name: string
        +author: string
        +cover: image
        +AddToCart(mangas: Manga[])
        +RemoveToCart()
    }

    class Cart {
        -id: int
        +user: User
        +mangas: Manga[]
        +dates: date
        +Finalize()
        +ResetCart()
    }

    User o-- FacebookSDK
    Cart --|> Manga

}
@enduml